#cloud-config

package_update: true
package_upgrade: true

apt:
  sources:
    github-cli:
      source: "deb [arch=amd64 signed-by=$KEY_FILE] https://cli.github.com/packages stable main"
      keyid: 23F3D4EA75716059
      keyserver: keyserver.ubuntu.com

packages:
  - git
  - curl
  - wget
  - gh
  - unzip

snap:
  commands:
    - snap install concierge --classic

runcmd:
  - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
  - sudo -u ubuntu curl https://raw.githubusercontent.com/seb4stien/bootstrap/refs/heads/main/post-install.sh -o /home/ubuntu/post-install.sh
  - chmod +x /home/ubuntu/post-install.sh
  - concierge -p k8s prepare --extra-snaps terraform
